# Makefile, GematriaFBC
# Version 0.1
# Type 'make all' to compile
# Based on an example from
# https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html#creating
# ------------------------------------------------------------------------------
all: GematriaFBC.bas
	fbc -v -w all GematriaFBC.bas -x gematriafbc
clean:
	$(RM) gematriafbc

